// Script để seed dữ liệu mẫu lên Firestore
// Cách sử dụng: Sử dụng nút "Seed Data" trong Admin Panel (icon refresh ở góc trên bên phải)
// Hoặc chạy app và vào Admin Panel để seed data

// Dữ liệu mẫu sẽ được thêm vào collection 'medicines' trong Firestore

final sampleMedicines = [
  {
    'name': 'Paracetamol 500mg',
    'price': 15000.0,
    'description': 'Thuốc giảm đau, hạ sốt. Dùng cho người lớn và trẻ em trên 12 tuổi.',
    'category': 'Giảm đau',
    'stock': 100,
    'manufacturer': 'Traphaco',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'name': 'Amoxicillin 500mg',
    'price': 25000.0,
    'description': 'Kháng sinh điều trị nhiễm khuẩn đường hô hấp, tiết niệu.',
    'category': 'Kháng sinh',
    'stock': 80,
    'manufacturer': 'Hậu Giang Pharma',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'name': 'Vitamin C 1000mg',
    'price': 30000.0,
    'description': 'Bổ sung vitamin C, tăng cường sức đề kháng.',
    'category': 'Vitamin',
    'stock': 150,
    'manufacturer': 'Domesco',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'name': 'Ibuprofen 400mg',
    'price': 20000.0,
    'description': 'Thuốc chống viêm, giảm đau, hạ sốt.',
    'category': 'Giảm đau',
    'stock': 90,
    'manufacturer': 'Pharmedic',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'name': 'Cefuroxime 250mg',
    'price': 45000.0,
    'description': 'Kháng sinh phổ rộng điều trị nhiễm khuẩn.',
    'category': 'Kháng sinh',
    'stock': 60,
    'manufacturer': 'Traphaco',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'name': 'Vitamin D3 2000IU',
    'price': 35000.0,
    'description': 'Bổ sung vitamin D3, hỗ trợ hấp thu canxi.',
    'category': 'Vitamin',
    'stock': 120,
    'manufacturer': 'Domesco',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'name': 'Dextromethorphan 15mg',
    'price': 18000.0,
    'description': 'Thuốc giảm ho, điều trị ho khan.',
    'category': 'Thuốc ho',
    'stock': 110,
    'manufacturer': 'Hậu Giang Pharma',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'name': 'Pseudoephedrine 60mg',
    'price': 22000.0,
    'description': 'Thuốc thông mũi, giảm nghẹt mũi do cảm cúm.',
    'category': 'Thuốc cảm',
    'stock': 95,
    'manufacturer': 'Pharmedic',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'name': 'Omeprazole 20mg',
    'price': 28000.0,
    'description': 'Thuốc điều trị viêm loét dạ dày, trào ngược dạ dày.',
    'category': 'Thuốc tiêu hóa',
    'stock': 85,
    'manufacturer': 'Traphaco',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'name': 'Amlodipine 5mg',
    'price': 40000.0,
    'description': 'Thuốc điều trị tăng huyết áp, đau thắt ngực.',
    'category': 'Thuốc tim mạch',
    'stock': 70,
    'manufacturer': 'Domesco',
    'imageUrl': '',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
];
